<Project>
  <PropertyGroup>
    <AbpVersion>10.2.1</AbpVersion>
    <GrpcVersion>2.71.0</GrpcVersion>
    <GrpcToolsVersion>2.72.0</GrpcToolsVersion>
    <DtmgrpcVersion>1.4.0</DtmgrpcVersion>
    <DtmMongoBarrierVersion>1.4.0</DtmMongoBarrierVersion>
    <GoogleProtobufVersion>3.32.0</GoogleProtobufVersion>
  </PropertyGroup>
</Project>